# Generated by Django 5.0.6 on 2026-06-08 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contactos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evolution_api_url', models.CharField(blank=True, max_length=200, verbose_name='Evolution API URL')),
                ('evolution_api_key', models.CharField(blank=True, max_length=200, verbose_name='API Key')),
                ('evolution_instance_name', models.CharField(blank=True, default='crm-supreg', max_length=100, verbose_name='Nombre de instancia')),
                ('webhook_token', models.CharField(blank=True, help_text='Token secreto que Evolution API envía en el header al hacer webhook', max_length=100, verbose_name='Token de webhook')),
            ],
            options={
                'verbose_name': 'Configuración WhatsApp',
                'verbose_name_plural': 'Configuración WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='LogAPIWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=10)),
                ('request_body', models.TextField(blank=True)),
                ('response_status', models.IntegerField(null=True)),
                ('response_body', models.TextField(blank=True)),
                ('duracion_ms', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exitoso', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Log API WhatsApp',
                'verbose_name_plural': 'Logs API WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaHSM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('idioma', models.CharField(default='es_AR', max_length=10)),
                ('cuerpo', models.TextField(help_text='Texto principal. Usar {{1}}, {{2}}... para variables.')),
                ('variables', models.JSONField(blank=True, default=list, help_text='Lista de nombres de variables en orden: ["nombre", "plan", ...]')),
                ('header_tipo', models.CharField(choices=[('none', 'Sin header'), ('text', 'Texto'), ('image', 'Imagen'), ('document', 'Documento'), ('video', 'Video')], default='none', max_length=10, verbose_name='Tipo de header')),
                ('header_contenido', models.TextField(blank=True, help_text='Texto del header (si tipo=Texto) o URL del archivo (imagen/video/documento)', verbose_name='Contenido del header')),
                ('footer', models.CharField(blank=True, help_text='Texto del pie de mensaje (máximo 60 caracteres)', max_length=60, verbose_name='Footer')),
                ('botones', models.JSONField(blank=True, default=list, help_text='[{"tipo":"reply","texto":"Sí, me interesa"},{"tipo":"url","texto":"Ver planes","valor":"https://..."}]', verbose_name='Botones')),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Mensaje',
                'verbose_name_plural': 'Plantillas de Mensaje',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='BotRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la regla')),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Menor número = mayor prioridad')),
                ('trigger_tipo', models.CharField(choices=[('primer_mensaje', 'Primer mensaje del contacto (bienvenida)'), ('palabra_clave', 'Contiene palabras clave')], max_length=20, verbose_name='Disparador')),
                ('palabras_clave', models.JSONField(blank=True, default=list, help_text='Lista de palabras/frases. Coincidencia parcial, sin distinción de mayúsculas. Ej: ["precio", "info", "quiero"]', verbose_name='Palabras clave')),
                ('respuesta_tipo', models.CharField(choices=[('texto', 'Texto libre'), ('plantilla', 'Plantilla HSM'), ('interactivo', 'Mensaje con botones')], default='texto', max_length=20)),
                ('respuesta_texto', models.TextField(blank=True, verbose_name='Texto de respuesta')),
                ('respuesta_interactivo_body', models.TextField(blank=True, verbose_name='Cuerpo del mensaje interactivo')),
                ('respuesta_interactivo_botones', models.JSONField(blank=True, default=list, help_text='[{"id":"btn_1","title":"Sí, quiero información"}]', verbose_name='Botones')),
                ('accion_prioridad', models.CharField(blank=True, help_text='Dejar vacío para no cambiar la prioridad', max_length=10, verbose_name='Cambiar prioridad del contacto a')),
                ('solo_si_sin_agente', models.BooleanField(default=False, verbose_name='Solo si no tiene agente asignado')),
                ('solo_primera_vez', models.BooleanField(default=True, verbose_name='Solo responder una vez por conversación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accion_stage', models.ForeignKey(blank=True, help_text='Dejar vacío para no cambiar la etapa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contactos.pipelinestage', verbose_name='Mover el contacto a la etapa')),
                ('respuesta_plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_reglas', to='whatsapp.plantillahsm', verbose_name='Plantilla HSM')),
            ],
            options={
                'verbose_name': 'Regla de bot',
                'verbose_name_plural': 'Reglas de bot WhatsApp',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nombre_contacto', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('abierta', 'Abierta'), ('cerrada', 'Cerrada')], db_index=True, default='pendiente', max_length=20, verbose_name='Estado')),
                ('ultimo_mensaje_at', models.DateTimeField(blank=True, null=True)),
                ('mensajes_no_leidos', models.PositiveIntegerField(default=0)),
                ('bot_crm_activo', models.BooleanField(default=True, verbose_name='Bot CRM activo')),
                ('bot_n8n_activo', models.BooleanField(default=True, verbose_name='Bot n8n activo')),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones', to=settings.AUTH_USER_MODEL)),
                ('contacto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversacion_whatsapp', to='contactos.contacto')),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'ordering': ['-ultimo_mensaje_at'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_message_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('direccion', models.CharField(choices=[('in', 'Entrante'), ('out', 'Saliente')], max_length=3)),
                ('tipo', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagen'), ('document', 'Documento'), ('audio', 'Audio'), ('video', 'Video'), ('template', 'Plantilla HSM'), ('interactive', 'Interactivo')], default='text', max_length=20)),
                ('contenido', models.TextField(blank=True)),
                ('media_url', models.URLField(blank=True, max_length=2000)),
                ('media_id', models.CharField(blank=True, max_length=100)),
                ('media_mime', models.CharField(blank=True, max_length=100)),
                ('media_filename', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('delivered', 'Entregado'), ('read', 'Leído'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('error_detalle', models.TextField(blank=True)),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_whatsapp', to='contactos.contacto')),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='whatsapp.conversacion')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LogBotRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondido_at', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_logs', to='whatsapp.conversacion')),
                ('regla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='whatsapp.botrespuesta')),
            ],
            options={
                'unique_together': {('conversacion', 'regla')},
            },
        ),
    ]
