# Generated by Django 5.0.6 on 2026-06-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacion',
            name='archivada',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Archivada'),
        ),
    ]
