# Generated by Django 5.0.6 on 2026-06-09 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_conversacion_archivada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaRapida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('atajo', models.CharField(help_text='Palabra clave sin barra (ej: "saludo"). Se activa con /saludo en el chat.', max_length=30, unique=True, verbose_name='Atajo')),
                ('texto', models.TextField(verbose_name='Texto de la respuesta')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_rapidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Respuesta rápida',
                'verbose_name_plural': 'Respuestas rápidas',
                'ordering': ['titulo'],
            },
        ),
    ]
