# Generated by Django 5.0.6 on 2026-06-08 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contactos', '0001_initial'),
        ('whatsapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaAutomatizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la regla')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(db_index=True, default=True, verbose_name='Activa')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden de ejecución')),
                ('modo', models.CharField(choices=[('automatizacion', '⚡ Automatización'), ('disparador', '🎯 Disparador')], db_index=True, default='automatizacion', max_length=20, verbose_name='Tipo de regla')),
                ('tiempo_tipo', models.CharField(choices=[('instant', 'Inmediatamente'), ('delay', 'En X tiempo'), ('date', 'Cuando un campo de fecha es igual a')], default='instant', max_length=10, verbose_name='Tiempo de ejecución')),
                ('tiempo_cantidad', models.PositiveSmallIntegerField(default=1, help_text='Para "En X tiempo"', verbose_name='Cantidad')),
                ('tiempo_unidad', models.CharField(choices=[('minutos', 'minutos'), ('horas', 'horas'), ('dias', 'días')], default='dias', max_length=10, verbose_name='Unidad')),
                ('tiempo_campo_fecha', models.CharField(blank=True, default='created_at', help_text='Para "Cuando un campo de fecha es igual a"', max_length=50, verbose_name='Campo de fecha de referencia')),
                ('tiempo_offset_dias', models.SmallIntegerField(default=0, help_text='Positivo = días después de la referencia, negativo = antes', verbose_name='Offset en días')),
                ('evento_tipo', models.CharField(choices=[('field_change', 'Cuando un campo cambia'), ('field_equals', 'Cuando un campo es igual a'), ('stage_change', 'Cuando cambia de etapa'), ('created', 'Al crear el contacto'), ('responsible_change', 'Cuando cambia el agente asignado'), ('webhook', 'Webhook externo recibido')], default='field_change', max_length=20, verbose_name='Evento')),
                ('evento_campo', models.CharField(blank=True, choices=[('', 'Cualquier campo'), ('stage', 'Etapa'), ('prioridad', 'Prioridad'), ('origen', 'Origen'), ('agente', 'Agente asignado'), ('tipo', 'Tipo de contacto')], help_text='Vacío = cualquier campo (solo para "Cuando un campo cambia")', max_length=50, verbose_name='Campo')),
                ('evento_operador', models.CharField(blank=True, choices=[('eq', 'es igual a'), ('neq', 'no es igual a'), ('gt', 'mayor que'), ('lt', 'menor que'), ('contains', 'contiene'), ('empty', 'está vacío'), ('not_empty', 'no está vacío')], max_length=15, verbose_name='Operador')),
                ('evento_valor', models.CharField(blank=True, max_length=200, verbose_name='Valor')),
                ('condiciones', models.JSONField(blank=True, default=list, help_text='Lista de condiciones [{campo, operador, valor, conector}]. Si está vacía, la regla siempre se ejecuta.', verbose_name='Condiciones')),
                ('accion_tipo', models.CharField(choices=[('field', 'Cambiar campo del contacto'), ('stage', 'Mover a otra etapa del pipeline'), ('assign', 'Asignar agente'), ('plantilla_wa', 'Enviar plantilla de WhatsApp'), ('mensaje_wa', 'Enviar mensaje de WhatsApp (texto libre)'), ('tarea', 'Crear tarea para el agente asignado'), ('webhook', 'Llamar webhook externo (n8n / URL)')], default='mensaje_wa', max_length=20, verbose_name='Acción')),
                ('accion_campo', models.CharField(blank=True, help_text='Nombre de campo (prioridad, origen, notas...) o slug de un campo personalizado', max_length=50, verbose_name='Campo a cambiar')),
                ('accion_valor', models.CharField(blank=True, max_length=200, verbose_name='Nuevo valor')),
                ('accion_mensaje_texto', models.TextField(blank=True, help_text='Podés usar {nombre}, {etapa}, {telefono}', verbose_name='Texto del mensaje')),
                ('accion_tarea_descripcion', models.TextField(blank=True, help_text='Podés usar {nombre} para el nombre del contacto.', verbose_name='Descripción de la tarea')),
                ('accion_tarea_dias_plazo', models.PositiveSmallIntegerField(default=1, help_text='Días desde hoy para la tarea', verbose_name='Plazo (días)')),
                ('accion_webhook_url', models.CharField(blank=True, max_length=500, verbose_name='URL del webhook')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accion_agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automatizaciones_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Agente a asignar')),
                ('accion_plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp.plantillahsm', verbose_name='Plantilla HSM')),
                ('accion_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contactos.pipelinestage', verbose_name='Etapa destino')),
                ('evento_stage_desde', models.ForeignKey(blank=True, help_text='Vacío = cualquier etapa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contactos.pipelinestage', verbose_name='Etapa de origen')),
                ('evento_stage_hasta', models.ForeignKey(blank=True, help_text='Vacío = cualquier etapa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contactos.pipelinestage', verbose_name='Etapa de destino')),
                ('tipo_contacto', models.ForeignKey(blank=True, help_text='Dejar vacío para aplicar a todos los tipos de contacto.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contactos.tipocontacto', verbose_name='Aplica a')),
            ],
            options={
                'verbose_name': 'Regla de automatización',
                'verbose_name_plural': 'Reglas de automatización',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='AutomatizacionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejecutado_at', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.TextField(blank=True)),
                ('exitoso', models.BooleanField(default=True)),
                ('evento', models.CharField(blank=True, help_text='Descripción del evento que disparó (para disparadores)', max_length=200)),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automatizacion_logs', to='contactos.contacto')),
                ('regla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='automations.reglaautomatizacion')),
            ],
            options={
                'verbose_name': 'Log de automatización',
                'verbose_name_plural': 'Logs de automatización',
                'ordering': ['-ejecutado_at'],
            },
        ),
    ]
