# Generated by Django 5.1.4 on 2026-06-16 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0005_reglaautomatizacion_entidad_filtros'),
        ('contactos', '0006_alter_pipeline_campos_tarjeta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejecucionflujo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='flujo',
            name='grafo',
            field=models.JSONField(blank=True, default=dict, help_text='Drawflow JSON: {drawflow:{Home:{data:{...}}}}'),
        ),
        migrations.AlterField(
            model_name='flujo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='flujo',
            name='trigger_config',
            field=models.JSONField(blank=True, default=dict, help_text='{"tipo_contacto_id": null} o {"etapa_id": 5} o {"dias": 3}'),
        ),
        migrations.AlterField(
            model_name='reglaautomatizacion',
            name='filtro_etapa',
            field=models.ForeignKey(blank=True, help_text='Si se especifica, solo se ejecuta cuando el contacto/deal está en esta etapa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contactos.pipelinestage', verbose_name='Solo en la etapa'),
        ),
        migrations.AlterField(
            model_name='reglaautomatizacion',
            name='filtro_pipeline',
            field=models.ForeignKey(blank=True, help_text='Si se especifica, solo se ejecuta para contactos cuyo pipeline activo sea este.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contactos.pipeline', verbose_name='Solo en el pipeline'),
        ),
        migrations.AlterField(
            model_name='reglaautomatizacion',
            name='tipo_contacto',
            field=models.ForeignKey(blank=True, help_text='Dejar vacío para aplicar a todos los tipos.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contactos.tipocontacto', verbose_name='Tipo de contacto'),
        ),
    ]
