# Generated by Django 5.1.4 on 2026-06-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0007_register_ejecutar_automatizaciones_beat'),
        ('contactos', '0007_alter_contacto_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatizacionlog',
            name='ejecutado_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='automatizacionlog',
            index=models.Index(fields=['regla', 'contacto'], name='automations_regla_i_46e3d2_idx'),
        ),
    ]
