# Generated by Django 5.0.6 on 2026-06-08 19:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True, verbose_name='Clave interna')),
                ('tipo', models.CharField(choices=[('texto', 'Texto libre'), ('numero', 'Número'), ('fecha', 'Fecha'), ('booleano', 'Sí / No'), ('lista', 'Lista de opciones')], default='texto', max_length=20, verbose_name='Tipo')),
                ('opciones', models.JSONField(blank=True, default=list, verbose_name='Opciones (para Lista)')),
                ('requerido', models.BooleanField(default=False, verbose_name='Requerido')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Campo personalizado',
                'verbose_name_plural': 'Campos personalizados',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pipeline',
                'verbose_name_plural': 'Pipelines',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('dni', models.CharField(blank=True, db_index=True, max_length=8, validators=[django.core.validators.RegexValidator(message='El DNI debe tener entre 7 y 8 dígitos numéricos.', regex='^\\d{7,8}$')], verbose_name='DNI')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('telefono', models.CharField(db_index=True, max_length=20, validators=[django.core.validators.RegexValidator(message='El teléfono debe incluir el código de país (ej: +5491122334455).', regex='^\\+\\d{10,15}$')], verbose_name='Teléfono (WhatsApp)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('localidad', models.CharField(blank=True, max_length=100, verbose_name='Localidad')),
                ('provincia', models.CharField(blank=True, max_length=100, verbose_name='Provincia')),
                ('grupo_familiar', models.PositiveSmallIntegerField(default=1, verbose_name='Cantidad grupo familiar')),
                ('origen', models.CharField(choices=[('web', 'Web'), ('campana', 'Campaña'), ('referido', 'Referido'), ('llamada', 'Llamada entrante'), ('whatsapp', 'WhatsApp')], default='web', max_length=20, verbose_name='Origen')),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10, verbose_name='Prioridad')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('motivo_perdida', models.TextField(blank=True, help_text='Completar cuando el contacto pasa a una etapa marcada como "cierre perdido".', verbose_name='Motivo de pérdida')),
                ('datos_extra', models.JSONField(blank=True, default=dict, help_text='Columnas adicionales importadas y valores de campos personalizados.', verbose_name='Datos extra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Agente asignado')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('recibo_sueldo', 'Recibo de sueldo'), ('dni', 'DNI'), ('contrato', 'Contrato / formulario'), ('otro', 'Otro')], default='otro', max_length=30, verbose_name='Tipo')),
                ('archivo', models.FileField(blank=True, upload_to='documentos/%Y/%m/', verbose_name='Archivo')),
                ('url_externa', models.URLField(blank=True, help_text='URL del archivo cuando no hay archivo local (ej: media de WhatsApp)', max_length=2000, verbose_name='URL externa')),
                ('fuente', models.CharField(choices=[('manual', 'Manual'), ('whatsapp', 'WhatsApp')], default='manual', max_length=20, verbose_name='Fuente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='contactos.contacto')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la etapa')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('color', models.CharField(choices=[('primary', 'Azul'), ('success', 'Verde'), ('warning', 'Amarillo'), ('danger', 'Rojo'), ('info', 'Celeste'), ('secondary', 'Gris'), ('dark', 'Oscuro')], default='primary', max_length=20, verbose_name='Color')),
                ('es_ganado', models.BooleanField(default=False, help_text='Ej: "Afiliado" o "Cerrado ganado". Útil para reportes y automatizaciones.', verbose_name='Etapa de cierre ganado')),
                ('es_perdido', models.BooleanField(default=False, help_text='Ej: "Perdido" o "Descartado". Habilita el campo "Motivo de pérdida".', verbose_name='Etapa de cierre perdido')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='contactos.pipeline')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'ordering': ['pipeline', 'orden', 'nombre'],
                'unique_together': {('pipeline', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='HistorialEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cambiado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_etapas', to='contactos.contacto')),
                ('etapa_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contactos.pipelinestage')),
                ('etapa_nueva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contactos.pipelinestage')),
            ],
            options={
                'verbose_name': 'Historial de etapa',
                'verbose_name_plural': 'Historial de etapas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contacto',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos', to='contactos.pipelinestage', verbose_name='Etapa'),
        ),
        migrations.CreateModel(
            name='CampoRegla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion_tipo', models.CharField(choices=[('siempre', 'Siempre'), ('etapa', 'Cuando la etapa del contacto es')], default='siempre', max_length=20)),
                ('accion', models.CharField(choices=[('obligatorio', 'Obligatorio'), ('visible', 'Visible'), ('oculto', 'Oculto'), ('solo_lectura', 'Solo lectura')], max_length=20)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas', to='contactos.campopersonalizado')),
                ('condicion_etapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contactos.pipelinestage', verbose_name='Etapa')),
            ],
            options={
                'verbose_name': 'Regla de campo',
                'verbose_name_plural': 'Reglas de campo',
                'ordering': ['campo', 'condicion_tipo'],
            },
        ),
        migrations.AddField(
            model_name='contacto',
            name='plan_interes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos', to='contactos.plan', verbose_name='Plan de interés'),
        ),
        migrations.CreateModel(
            name='TipoContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('nombre_plural', models.CharField(blank=True, max_length=100, verbose_name='Nombre plural')),
                ('color', models.CharField(choices=[('primary', 'Azul'), ('success', 'Verde'), ('warning', 'Amarillo'), ('danger', 'Rojo'), ('info', 'Celeste'), ('secondary', 'Gris'), ('dark', 'Oscuro')], default='primary', max_length=20, verbose_name='Color')),
                ('icono', models.CharField(blank=True, default='person', help_text='Nombre de ícono Bootstrap, sin el prefijo "bi-" (ej: person, briefcase)', max_length=50, verbose_name='Ícono')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('es_sistema', models.BooleanField(default=False, editable=False, help_text='Tipos base del sistema (lead, cliente): no se pueden eliminar.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_contacto', to='contactos.pipeline', verbose_name='Pipeline / ciclo de vida')),
            ],
            options={
                'verbose_name': 'Tipo de contacto',
                'verbose_name_plural': 'Tipos de contacto',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='contacto',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contactos', to='contactos.tipocontacto', verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='campopersonalizado',
            name='tipo_contacto',
            field=models.ForeignKey(blank=True, help_text='Dejar vacío para que el campo aplique a todos los tipos de contacto.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campos_personalizados', to='contactos.tipocontacto', verbose_name='Aplica a'),
        ),
    ]
