# Generated by Django 5.0.6 on 2026-06-09 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('color', models.CharField(choices=[('primary', 'Azul'), ('success', 'Verde'), ('warning', 'Amarillo'), ('danger', 'Rojo'), ('info', 'Celeste'), ('secondary', 'Gris'), ('dark', 'Oscuro')], default='secondary', max_length=20, verbose_name='Color')),
                ('slug', models.SlugField(editable=False, max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='contacto',
            name='stage_updated_at',
            field=models.DateTimeField(blank=True, help_text='Se actualiza automáticamente al cambiar de etapa.', null=True, verbose_name='Última actualización de etapa'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='notas',
            field=models.TextField(blank=True, verbose_name='Notas internas (legacy)'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='contactos', to='contactos.etiqueta', verbose_name='Etiquetas'),
        ),
        migrations.CreateModel(
            name='NotaContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_crm', to=settings.AUTH_USER_MODEL)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_internas', to='contactos.contacto')),
                ('menciones', models.ManyToManyField(blank=True, related_name='notas_mencionado', to=settings.AUTH_USER_MODEL, verbose_name='Menciones')),
            ],
            options={
                'verbose_name': 'Nota interna',
                'verbose_name_plural': 'Notas internas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FiltroGuardado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('parametros', models.JSONField(default=dict, verbose_name='Parámetros de filtro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tipo_contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contactos.tipocontacto', verbose_name='Tipo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filtros_guardados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Filtro guardado',
                'verbose_name_plural': 'Filtros guardados',
                'ordering': ['nombre'],
                'unique_together': {('usuario', 'nombre')},
            },
        ),
    ]
