# Generated by Django 5.0.6 on 2026-06-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0002_etiquetas_notas_filtros'),
    ]

    operations = [
        migrations.AddField(
            model_name='campopersonalizado',
            name='entidad',
            field=models.CharField(choices=[('contacto', 'Contacto'), ('negociacion', 'Negociación')], default='contacto', help_text='Define si el campo se gestiona en la ficha de Contactos o de Negociaciones.', max_length=20, verbose_name='Tipo de registro'),
        ),
    ]
