# Generated by Django 5.1.4 on 2026-06-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0005_campopersonalizado_tipo_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='campos_tarjeta',
            field=models.JSONField(blank=True, default=list, help_text='Slugs de campos a mostrar en las tarjetas del kanban.', verbose_name='Campos en tarjeta kanban'),
        ),
        migrations.AlterField(
            model_name='pipelinestage',
            name='campos_requeridos',
            field=models.JSONField(blank=True, default=list, help_text='Slugs de campos que el contacto debe tener completados para avanzar a esta etapa.', verbose_name='Campos requeridos para entrar'),
        ),
    ]
