# Generated by Django 5.1.4 on 2026-06-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0006_alter_pipeline_campos_tarjeta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
