# Generated by Django 5.1.4 on 2026-06-18 21:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0007_alter_contacto_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='historialetapa',
            index=models.Index(fields=['contacto', '-created_at'], name='contactos_h_contact_45134c_idx'),
        ),
    ]
