# Generated by Django 5.0.6 on 2026-06-08 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contactos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_integrantes', models.PositiveSmallIntegerField(default=1)),
                ('monto_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='borrador', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='cotizaciones/pdf/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='contactos.contacto')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contactos.plan')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegranteFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=8)),
                ('fecha_nacimiento', models.DateField()),
                ('parentesco', models.CharField(choices=[('titular', 'Titular'), ('conyuge', 'Cónyuge'), ('hijo', 'Hijo/a'), ('otro', 'Otro')], default='titular', max_length=20)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrantes', to='quotes.cotizacion')),
            ],
            options={
                'verbose_name': 'Integrante familiar',
                'verbose_name_plural': 'Integrantes familiares',
            },
        ),
    ]
