# Generated by Django 5.0.6 on 2026-06-08 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contactos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor estimado ($)')),
                ('nombre_contacto', models.CharField(blank=True, max_length=200, verbose_name='Nombre del contacto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción / notas')),
                ('fecha_cierre_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha de cierre estimada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to=settings.AUTH_USER_MODEL, verbose_name='Agente responsable')),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='contactos.contacto', verbose_name='Contacto asociado')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='contactos.pipeline', verbose_name='Pipeline')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='contactos.pipelinestage', verbose_name='Etapa')),
            ],
            options={
                'verbose_name': 'Negociación',
                'verbose_name_plural': 'Negociaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cambiado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='deals.deal')),
                ('stage_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contactos.pipelinestage')),
                ('stage_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contactos.pipelinestage')),
            ],
            options={
                'verbose_name': 'Historial de etapa',
                'verbose_name_plural': 'Historial de etapas',
                'ordering': ['-created_at'],
            },
        ),
    ]
