# Generated by Django 5.0.6 on 2026-06-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='datos_extra',
            field=models.JSONField(blank=True, default=dict, verbose_name='Datos adicionales'),
        ),
    ]
