# Generated by Django 5.1.4 on 2026-06-18 21:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0008_historialetapa_contactos_h_contact_45134c_idx'),
        ('deals', '0002_deal_datos_extra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dealhistory',
            index=models.Index(fields=['deal', '-created_at'], name='deals_dealh_deal_id_1f855c_idx'),
        ),
    ]
