# Generated by Django 5.1.4 on 2026-06-16 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatbotflow',
            options={'verbose_name': 'Flujo de chatbot', 'verbose_name_plural': 'Flujos de chatbot'},
        ),
    ]
