# Generated by Django 5.0.6 on 2026-06-09 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_disponible'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('lead_asignado', 'Lead asignado'), ('tarea_vencida', 'Tarea vencida'), ('mencion_nota', 'Mención en nota')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('cuerpo', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('leida', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación interna',
                'verbose_name_plural': 'Notificaciones internas',
                'ordering': ['-created_at'],
            },
        ),
    ]
