# Generated by Django 5.0.6 on 2026-06-08 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contactos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('llamada', 'Llamada'), ('whatsapp', 'WhatsApp'), ('reunion', 'Reunión'), ('documentacion', 'Envío de documentación'), ('seguimiento', 'Seguimiento')], default='seguimiento', max_length=20)),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_programada', models.DateTimeField(verbose_name='Fecha y hora programada')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('vencida', 'Vencida')], db_index=True, default='pendiente', max_length=20)),
                ('resultado', models.TextField(blank=True, verbose_name='Resultado / nota de completado')),
                ('notificacion_enviada', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to=settings.AUTH_USER_MODEL)),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='contactos.contacto')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['fecha_programada'],
            },
        ),
    ]
