# Generated by Django 5.0.6 on 2026-06-08 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contactos', '0001_initial'),
        ('whatsapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('modo_seleccion', models.CharField(choices=[('segmento', 'Por segmento (filtros automáticos)'), ('manual', 'Selección manual de contactos')], default='segmento', max_length=10)),
                ('filtros_segmento', models.JSONField(blank=True, default=dict)),
                ('contactos_ids', models.JSONField(blank=True, default=list, verbose_name='Contactos seleccionados')),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('programada', 'Programada'), ('en_ejecucion', 'En ejecución'), ('completada', 'Completada')], default='borrador', max_length=20)),
                ('fecha_programada', models.DateTimeField(blank=True, null=True)),
                ('variables_mapping', models.JSONField(blank=True, default=list)),
                ('total_destinatarios', models.PositiveIntegerField(default=0)),
                ('enviados', models.PositiveIntegerField(default=0)),
                ('entregados', models.PositiveIntegerField(default=0)),
                ('leidos', models.PositiveIntegerField(default=0)),
                ('errores', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='whatsapp.plantillahsm')),
                ('tipo_contacto', models.ForeignKey(blank=True, help_text='Dejar vacío para incluir todos los tipos.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contactos.tipocontacto', verbose_name='Tipo de destinatarios')),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Campañas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampanaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20)),
                ('nombre_contacto', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('enviado', 'Enviado'), ('error', 'Error')], max_length=10)),
                ('whatsapp_message_id', models.CharField(blank=True, max_length=100)),
                ('error_detalle', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='campaigns.campana')),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campana_logs', to='contactos.contacto')),
            ],
            options={
                'verbose_name': 'Log de campaña',
                'verbose_name_plural': 'Logs de campaña',
            },
        ),
    ]
